import bcrypt from 'bcryptjs';

type PostgresQueryable = {
  query: (sql: string, params?: readonly unknown[]) => Promise<unknown>;
};

function quoteIdentifier(identifier: string): string {
  return `"${String(identifier || 'public').replace(/"/g, '""')}"`;
}

const POSTGRES_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'technician',
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY,
    business_name TEXT DEFAULT 'Milo Pro',
    business_address TEXT,
    business_phone TEXT,
    business_email TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sku_sequence_migrated INTEGER DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT,
    description TEXT,
    parent_id INTEGER REFERENCES categories(id),
    woocommerce_category_id INTEGER,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS device_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active INTEGER DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS brands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT,
    woocommerce_brand_id INTEGER,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS device_models (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id INTEGER REFERENCES brands(id),
    name TEXT NOT NULL,
    active INTEGER DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    contact TEXT,
    city TEXT,
    province TEXT,
    country TEXT,
    tax_id TEXT,
    iva_condition TEXT DEFAULT 'Consumidor Final',
    instagram TEXT,
    transport TEXT,
    credit_limit DOUBLE PRECISION DEFAULT 0,
    zone TEXT,
    discount_percent DOUBLE PRECISION DEFAULT 0,
    seller TEXT,
    price_list TEXT DEFAULT '1',
    billing_conditions TEXT,
    external_source TEXT,
    external_customer_id TEXT,
    is_generic INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS suppliers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    city TEXT,
    tax_id TEXT,
    notes TEXT,
    total_purchases DOUBLE PRECISION DEFAULT 0,
    total_credits DOUBLE PRECISION DEFAULT 0,
    total_payments DOUBLE PRECISION DEFAULT 0,
    balance DOUBLE PRECISION DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE,
    barcode TEXT,
    name TEXT NOT NULL,
    description TEXT,
    short_description TEXT,
    color TEXT,
    category_id INTEGER REFERENCES categories(id),
    category_primary_id INTEGER REFERENCES categories(id),
    brand_id INTEGER REFERENCES brands(id),
    supplier TEXT,
    purchase_price DOUBLE PRECISION DEFAULT 0,
    sale_price DOUBLE PRECISION DEFAULT 0,
    sale_price_includes_tax INTEGER DEFAULT 1,
    sale_price_2 DOUBLE PRECISION DEFAULT 0,
    sale_price_2_includes_tax INTEGER DEFAULT 0,
    sale_price_3 DOUBLE PRECISION DEFAULT 0,
    sale_price_3_includes_tax INTEGER DEFAULT 0,
    sale_price_4 DOUBLE PRECISION DEFAULT 0,
    sale_price_4_includes_tax INTEGER DEFAULT 0,
    sale_price_5 DOUBLE PRECISION DEFAULT 0,
    sale_price_5_includes_tax INTEGER DEFAULT 0,
    sale_price_6 DOUBLE PRECISION DEFAULT 0,
    sale_price_6_includes_tax INTEGER DEFAULT 0,
    stock INTEGER DEFAULT 0,
    min_stock INTEGER DEFAULT 2,
    woocommerce_id INTEGER,
    woocommerce_product_id INTEGER,
    image_url TEXT,
    sync_status TEXT DEFAULT 'pending',
    last_sync_at TIMESTAMP,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER REFERENCES suppliers(id),
    invoice_type TEXT DEFAULT 'FA',
    invoice_number TEXT,
    invoice_date DATE,
    subtotal DOUBLE PRECISION DEFAULT 0,
    iva DOUBLE PRECISION DEFAULT 0,
    total DOUBLE PRECISION DEFAULT 0,
    notes TEXT,
    status TEXT DEFAULT 'pending',
    user_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS purchase_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id INTEGER NOT NULL REFERENCES purchases(id),
    product_id INTEGER REFERENCES products(id),
    product_name TEXT NOT NULL,
    product_code TEXT,
    quantity INTEGER NOT NULL,
    unit_cost DOUBLE PRECISION NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
    amount DOUBLE PRECISION NOT NULL,
    payment_method TEXT DEFAULT 'cash',
    reference TEXT,
    notes TEXT,
    user_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_credits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
    credit_note_number TEXT NOT NULL,
    reference_invoice TEXT,
    invoice_date DATE,
    subtotal DOUBLE PRECISION DEFAULT 0,
    iva DOUBLE PRECISION DEFAULT 0,
    total DOUBLE PRECISION DEFAULT 0,
    notes TEXT,
    status TEXT DEFAULT 'pending',
    user_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_credit_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_id INTEGER NOT NULL REFERENCES supplier_credits(id),
    product_id INTEGER REFERENCES products(id),
    product_name TEXT NOT NULL,
    product_code TEXT,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_account (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL UNIQUE REFERENCES suppliers(id),
    total_purchases DOUBLE PRECISION DEFAULT 0,
    total_credits DOUBLE PRECISION DEFAULT 0,
    total_payments DOUBLE PRECISION DEFAULT 0,
    balance DOUBLE PRECISION DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS supplier_account_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
    type TEXT NOT NULL,
    reference_id INTEGER,
    reference_number TEXT,
    description TEXT,
    debit DOUBLE PRECISION DEFAULT 0,
    credit DOUBLE PRECISION DEFAULT 0,
    balance DOUBLE PRECISION DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customers(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    channel TEXT DEFAULT 'local',
    status TEXT DEFAULT 'completed',
    payment_status TEXT DEFAULT 'paid',
    external_status TEXT,
    currency TEXT DEFAULT 'ARS',
    subtotal DOUBLE PRECISION DEFAULT 0,
    discount_total DOUBLE PRECISION DEFAULT 0,
    tax_total DOUBLE PRECISION DEFAULT 0,
    shipping_total DOUBLE PRECISION DEFAULT 0,
    receipt_type TEXT DEFAULT 'C',
    point_of_sale TEXT DEFAULT '001',
    receipt_number INTEGER DEFAULT 1,
    total DOUBLE PRECISION NOT NULL,
    total_paid DOUBLE PRECISION DEFAULT 0,
    external_reference TEXT,
    payment_method TEXT DEFAULT 'cash',
    notes TEXT,
    external_created_at TIMESTAMP,
    external_updated_at TIMESTAMP,
    stock_applied_at TIMESTAMP,
    stock_applied_state TEXT,
    stock_reverted_at TIMESTAMP,
    stock_reverted_state TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS cash_movements (
    id SERIAL PRIMARY KEY,
    type TEXT NOT NULL,
    date TEXT NOT NULL,
    description TEXT NOT NULL,
    person TEXT,
    amount DOUBLE PRECISION NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sellers (
    id TEXT PRIMARY KEY,
    code TEXT,
    name TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    cell TEXT,
    commission_percent DOUBLE PRECISION DEFAULT 5,
    archived INTEGER DEFAULT 0,
    source TEXT DEFAULT 'manual',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS seller_commission_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_date TEXT NOT NULL,
    seller_id TEXT NOT NULL,
    seller_name TEXT NOT NULL,
    total_paid DOUBLE PRECISION NOT NULL,
    total_sales DOUBLE PRECISION DEFAULT 0,
    sale_ids_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS admin_connected_sessions (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    ip TEXT,
    login_date TEXT,
    last_activity TEXT,
    connection_status TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS admin_config_store (
    id INTEGER PRIMARY KEY,
    general_json TEXT,
    documents_json TEXT,
    mail_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS admin_aux_rows (
    id TEXT PRIMARY KEY,
    table_key TEXT NOT NULL,
    description TEXT NOT NULL,
    code TEXT,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS product_movements (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    product_id INTEGER REFERENCES products(id),
    date TEXT NOT NULL,
    code TEXT NOT NULL,
    description TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    reference TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sale_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL REFERENCES sales(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    external_line_id TEXT,
    external_product_id TEXT,
    sku TEXT,
    product_name TEXT,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS repairs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number TEXT UNIQUE NOT NULL,
    customer_id INTEGER NOT NULL REFERENCES customers(id),
    device_type TEXT NOT NULL,
    brand TEXT,
    model TEXT,
    serial_number TEXT,
    imei TEXT,
    password TEXT,
    pattern TEXT,
    problem_description TEXT NOT NULL,
    accessories TEXT,
    status TEXT DEFAULT 'received',
    estimated_price DOUBLE PRECISION,
    final_price DOUBLE PRECISION,
    technician_notes TEXT,
    entry_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delivery_date TIMESTAMP,
    customer_signature TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS repair_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_id INTEGER NOT NULL REFERENCES repairs(id),
    status TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS woocommerce_sync (
    id INTEGER PRIMARY KEY,
    store_url TEXT,
    consumer_key TEXT,
    consumer_secret TEXT,
    wp_username TEXT,
    wp_app_password TEXT,
    api_version TEXT DEFAULT 'wc/v3',
    sync_direction TEXT DEFAULT 'export',
    sync_products INTEGER DEFAULT 1,
    sync_customers INTEGER DEFAULT 0,
    sync_orders INTEGER DEFAULT 1,
    sync_stock INTEGER DEFAULT 1,
    sync_prices INTEGER DEFAULT 1,
    sync_mode TEXT DEFAULT 'manual',
    sync_interval_minutes INTEGER DEFAULT 60,
    tax_mode TEXT DEFAULT 'woocommerce',
    category_mode TEXT DEFAULT 'milo',
    conflict_priority TEXT DEFAULT 'milo',
    order_status_map TEXT DEFAULT '{"pending":"pendiente","processing":"procesando","completed":"completado","cancelled":"cancelado","refunded":"reintegrado","failed":"fallido"}',
    order_stock_statuses TEXT DEFAULT '["paid","completed"]',
    order_paid_statuses TEXT DEFAULT '["paid","completed"]',
    order_sync_mode TEXT DEFAULT 'webhook',
    order_sales_channel TEXT DEFAULT 'woocommerce',
    customer_sync_strategy TEXT DEFAULT 'create_or_link',
    generic_customer_name TEXT DEFAULT 'Cliente WooCommerce',
    webhook_secret TEXT,
    webhook_auth_token TEXT,
    webhook_signature_header TEXT DEFAULT 'x-wc-webhook-signature',
    webhook_delivery_header TEXT DEFAULT 'x-wc-webhook-delivery-id',
    last_sync TIMESTAMP,
    auto_sync INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS product_sync_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milo_id INTEGER,
    woocommerce_id INTEGER,
    action TEXT,
    status TEXT,
    message TEXT,
    synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS external_order_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    channel TEXT NOT NULL,
    woocommerce_order_id INTEGER NOT NULL,
    woocommerce_order_key TEXT,
    local_sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    external_reference TEXT NOT NULL,
    sync_state TEXT DEFAULT 'synced',
    last_error TEXT,
    last_payload TEXT,
    first_synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(channel, woocommerce_order_id),
    UNIQUE(channel, woocommerce_order_key),
    UNIQUE(channel, external_reference)
  )`,
  `CREATE TABLE IF NOT EXISTS sync_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    external_id TEXT,
    event_type TEXT,
    delivery_id TEXT,
    status TEXT NOT NULL,
    message TEXT,
    error TEXT,
    payload TEXT,
    context TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS product_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    es_principal INTEGER DEFAULT 0,
    orden INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id, category_id)
  )`,
  `CREATE TABLE IF NOT EXISTS product_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    nombre_archivo TEXT,
    ruta_local TEXT,
    url_publica TEXT,
    url_local TEXT,
    url_remote TEXT,
    woocommerce_media_id INTEGER,
    orden INTEGER DEFAULT 0,
    es_principal INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`,
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_sales_external_reference ON sales(external_reference)',
  'CREATE INDEX IF NOT EXISTS idx_sales_channel_status ON sales(channel, status)',
  'CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON sale_items(sale_id)',
  'CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email)',
  'CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone)',
  'CREATE INDEX IF NOT EXISTS idx_sync_logs_external_id ON sync_logs(external_id, created_at)'
] as const;

export async function bootstrapPostgresSchema(client: PostgresQueryable, schema: string): Promise<void> {
  const schemaName = String(schema || 'public').trim() || 'public';
  const quotedSchema = quoteIdentifier(schemaName);

  await client.query(`CREATE SCHEMA IF NOT EXISTS ${quotedSchema}`);
  await client.query(`SET search_path TO ${quotedSchema}`);

  for (const statement of POSTGRES_SCHEMA_STATEMENTS) {
    await client.query(statement);
  }

  await client.query("INSERT INTO settings (id, business_name) VALUES (1, 'Milo Pro') ON CONFLICT (id) DO NOTHING");
  await client.query(
    `
      INSERT INTO admin_config_store (id, general_json, documents_json, mail_json)
      VALUES (1, $1, $2, $3)
      ON CONFLICT (id) DO NOTHING
    `,
    [
      JSON.stringify({
        legal_name: '',
        tax_id: '',
        currency: 'ARS',
        date_format: 'dd/MM/yyyy',
        timezone: 'America/Argentina/Buenos_Aires',
        logo_name: '',
        logo_data_url: ''
      }),
      JSON.stringify({
        numbering_format: 'PV-00000000',
        prefixes: '',
        control_stock: true,
        allow_negative_stock: false,
        control_min_price: false,
        decimals: 2
      }),
      JSON.stringify({
        smtp_server: '',
        port: '587',
        username: '',
        password: '',
        encryption: 'tls',
        sender_email: ''
      })
    ]
  );
  await seedPostgresBaseline(client);
}

export { quoteIdentifier };

async function seedPostgresBaseline(client: PostgresQueryable): Promise<void> {
  const shouldSeed = String(process.env.MILO_DISABLE_SEED || '').trim() !== '1';
  if (!shouldSeed) {
    return;
  }

  const userCountResult = await client.query('SELECT COUNT(*)::int AS count FROM users');
  const userCount = Number((userCountResult as { rows?: Array<{ count?: number }> }).rows?.[0]?.count || 0);

  if (userCount > 0) {
    return;
  }

  const adminPassword = bcrypt.hashSync('admin123', 10);
  const techPassword = bcrypt.hashSync('tech123', 10);

  await client.query(
    "INSERT INTO users (username, password, role, name) VALUES ('admin', $1, 'admin', 'Administrator')",
    [adminPassword]
  );
  await client.query(
    "INSERT INTO users (username, password, role, name) VALUES ('tech', $1, 'technician', 'Technician')",
    [techPassword]
  );

  const categories = [
    { name: 'Computers', description: 'Laptops and Desktops' },
    { name: 'Cellphones', description: 'Mobile phones and smartphones' },
    { name: 'Tablets', description: 'iPads and Android tablets' },
    { name: 'Consoles', description: 'Video game consoles' },
    { name: 'Accessories', description: 'Cases, chargers, cables' },
    { name: 'Spare Parts', description: 'Screens, batteries, components' },
    { name: 'Networking', description: 'Routers, modems, adapters' },
    { name: 'Audio', description: 'Headphones, speakers' }
  ];

  for (const category of categories) {
    await client.query(
      'INSERT INTO categories (name, description) VALUES ($1, $2)',
      [category.name, category.description]
    );
  }

  const products = [
    { sku: 'LAP-001', name: 'HP Laptop 15s', category_id: 1, supplier: 'HP Distributor', purchase_price: 450, sale_price: 549, stock: 5 },
    { sku: 'LAP-002', name: 'Dell Inspiron 15', category_id: 1, supplier: 'Dell Inc', purchase_price: 520, sale_price: 649, stock: 3 },
    { sku: 'CEL-001', name: 'iPhone 14 Case', category_id: 2, supplier: 'CaseWorld', purchase_price: 8, sale_price: 19.99, stock: 50 },
    { sku: 'CEL-002', name: 'Samsung Galaxy Screen Protector', category_id: 2, supplier: 'ScreenPro', purchase_price: 3, sale_price: 12.99, stock: 100 },
    { sku: 'ACC-001', name: 'USB-C Cable 1m', category_id: 5, supplier: 'CableCo', purchase_price: 5, sale_price: 14.99, stock: 30 },
    { sku: 'ACC-002', name: 'Wireless Mouse', category_id: 5, supplier: 'Logitech', purchase_price: 15, sale_price: 29.99, stock: 15 },
    { sku: 'CON-001', name: 'PS5 Controller', category_id: 4, supplier: 'Sony', purchase_price: 45, sale_price: 64.99, stock: 8 },
    { sku: 'SPA-001', name: 'iPhone Battery', category_id: 6, supplier: 'PartsWorld', purchase_price: 35, sale_price: 59.99, stock: 10 },
    { sku: 'NET-001', name: 'TP-Link Router', category_id: 7, supplier: 'TP-Link', purchase_price: 25, sale_price: 45, stock: 7 },
    { sku: 'AUD-001', name: 'Bluetooth Headphones', category_id: 8, supplier: 'AudioTech', purchase_price: 20, sale_price: 39.99, stock: 12 }
  ];

  for (const product of products) {
    await client.query(
      `
        INSERT INTO products (sku, name, category_id, supplier, purchase_price, sale_price, stock)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
      `,
      [
        product.sku,
        product.name,
        product.category_id,
        product.supplier,
        product.purchase_price,
        product.sale_price,
        product.stock
      ]
    );
  }
}
